### ISSUE TITLE
minifying several files in a particular order

### ISSUE THREAD

**Issue by soloproyectos** [fizker/minifier#10]
I would like to minify several files into one file in a particular order. For example:
```JavaScript
var minifier = require('minifier');
minifier.minify('src/js/file1.js src/js/file2.js', {
    output: 'dist/jquery.sp-modal.min.js'
});
```
file1.js should be minified before file2.js and the result should be concatenated in the same file. But the previous example doesn't work.

Thanks for this great tool.

**Comment by fizker** [comment]
This should be possible from v. 0.7.1 by passing an array into the interface:

```js
var minifier = require('minifier');
minifier.minify(['src/js/file1.js', 'src/js/file2.js'], {
    output: 'dist/jquery.sp-modal.min.js'
});
```
