### ISSUE TITLE
Reading from stdin

### ISSUE THREAD

**Issue by mrzool** [fizker/minifier#11]
Is reading from `stdin` not supported?

This is what I get if I try to use `minify` after a pipe:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:849:11)
    at exports._exceptionWithHostPort (util.js:872:20)
    at WriteWrap.afterWrite (net.js:760:14)
```

**Comment by fizker** [comment]
No, it is not supported. I usually point it at a folder and let it glob for the files to minify, so I have never had a reason to pipe stuff into it.

**Comment by mrzool** [comment]
Fair enough. I was experimenting with my package.json, trying to come up with a pipe chain to compile some css using only CLI utilities (after reading [this](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/)).

I was looking for something along the lines of `cat css/*.css | minify` but that's obviously not going to work. Luckily, [cssnano](http://cssnano.co/) supports what I'm looking for. Thanks for the answer.

**Comment by fizker** [comment]
What I usually do is have a main css file which uses `@import` to properly order the files (which makes the cascade happy), and then use this project to minify it. It automatically resolves the `@import`, so there is no hit in production.
