### ISSUE TITLE
How to install it on a server using only PHP/FTP

### ISSUE THREAD

**Issue by Dakoom** [fizker/minifier#12]
Hi there, I'd like to run this script as a tool on my website, but I don't want to run any command lines. I would like just to use it and configure it as a normal script but I don't know where to start. Could you help me please? 

Everything I know so far: download the repository, upload all the content in my desired webfolder... then? If I create a .php file, what should I insert in it? What about the HTML form for sending the requests? I really don't know where to start. 
Thank you a lot in advance for any reply!

**Comment by fizker** [comment]
You can't. It requires [nodejs](https://nodejs.org) to run, so the PHP runtime is not good enough. And it cannot run in the browser either.
