### ISSUE TITLE
fails to compress multiple css files from command line

### ISSUE THREAD

**Issue by frumbert** [fizker/minifier#13]
I'm using this like this:

    minify --output app.min.css file1.css file2.css file3.css

but the output file only contains the minified contents of `file1.css`

performing the same type of operation with javascript files seems to work fine.

**Comment by fizker** [comment]
You can work around this by giving it a CSS file with the following content:

```css
@import url(file1.css);
@import url(file2.css);
@import url(file3.css);
```

It will resolve the `@import` and inline the results.

The beauty is that you can use this in development and only have to change one url between dev and prod. This is usually how I do it.
