### ISSUE TITLE
Doesn't end the last prop declaration with a semicolon. Is it possible to change?

### ISSUE THREAD

**Issue by wzup** [fizker/minifier#14]
When `minifier` is used as a CLI tool, it generates css removing a semicolon from the last prop declaration:

![css min 2016-01-25 13 43 33](https://cloud.githubusercontent.com/assets/3880497/12543363/c24d771e-c369-11e5-808d-be89af5f99ee.png)

Is is possible to change this behavior? So that it adds a semicolon always. https://google.github.io/styleguide/htmlcssguide.xml

**Comment by fizker** [comment]
It uses [sqwish](https://github.com/ded/sqwish) for the css minification, so ask them. My guess is no.

Also, why would you care? Minified code is not meant to be human-readable, that's what the original is for
