### ISSUE TITLE
Cannot concatenate multiple CSS

### ISSUE THREAD

**Issue by andela-abankole** [fizker/minifier#17]
Minifies first index of the provided array 😭

**Comment by karneaud** [comment]
+1

**Comment by fizker** [comment]
I have some ideas as to a fix. I'll toss some time after it in the weekend and see if my hunch plays out.

**Comment by fizker** [comment]
I didn't exactly hit the weekend, but we got there eventually ^^.
It should be fixed in v0.8.0. Please note that I bumped the required version of nodejs as well, to require the 4.x branch. Mostly because it pains me to write JS without arrow-functions :P.

**Comment by andela-abankole** [comment]
Thanks @fizker I understand
