### ISSUE TITLE
README has incorrect default behavior

### ISSUE THREAD

**Issue by brollb** [fizker/minifier#21]
In the readme, it says that omitting a path will result in a new file created next to the original w/ a ".min" added although omitting the `--output` flag results in the result being printed to stdout

**Comment by fizker** [comment]
That sounds weird. It works as advertised in my tests, and the output from the minification is handed directly to `fs.writeFileSync()` (https://github.com/fizker/minifier/blob/v0.8.0/src/minify.js#L130, https://github.com/fizker/minifier/blob/v0.8.0/src/minify.js#L151), so I can't see how it could end up in `stdout`.

Could it be that you have another executable with the same name? The name is quite generic, after all.

**Comment by ericmacfa** [comment]
I also get the result of `minify example.js` printed to stdout...not sure what the issue is

**Comment by brollb** [comment]
Yeah, I think this is my bad - sorry!
