### ISSUE TITLE
[help] error min js

### ISSUE THREAD

**Issue by wiloke1** [fizker/minifier#28]
undefined:1625
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
SyntaxError: Unexpected token: punc (.)
    at JS_Parse_Error.get (eval at <anonymous> (F:\Project\node_modules\minifier\node_modules\uglify-js\tools\node.js:27:1), <anonymous>:86:23)
events.js:182
      throw er; // Unhandled 'error' event

**Comment by fizker** [comment]
This sounds like a duplicate of #19, in that the version of uglifyjs used only supports ES5 syntax, and it sounds like your code might include rest syntax (`function a(...args)`

**Comment by long-hp** [comment]
tks @fizker
