### ISSUE TITLE
@import google font

### ISSUE THREAD

**Issue by evliu** [fizker/minifier#9]
hi,

first line of my css is ```@import url(http://fonts.googleapis.com/css?family=......```

outputs error: ```Error: ENOENT, no such file or directory 'http:/fonts.googleapis.com/css?family=......```

thoughts?

**Comment by fizker** [comment]
Yes. Currently, there are no support for files not located on the local disk. The error comes from trying to open the file and read the content.

For this project, I would probably start by dodging the bullet and simply not touch `@import`'s for non-local resources.

**Comment by fizker** [comment]
@evliu I have updated the underlying module, which does the CSS parsing. Can you please check if `npm update css-resolve-import` solves your issue? It should update said module to version 0.0.2.

**Comment by evliu** [comment]
i still get the same issue. I checked that css-resolve-import is at 0.0.2

**Comment by fizker** [comment]
I looked a bit closer at it, and found some issues with the unit tests. If you repeat the steps above, you should now get `css-resolve-import@0.0.3`, which solves it in my projects. Please check if this fixes it for you as well.

**Comment by evliu** [comment]
works, thx!!

**Comment by gerhardsletten** [comment]
Hi, got a similar problem when I just installed it from npm, seems the package.js file is not updated to css-resolve-import@0.0.3:

```
"dependencies": {
    "commander": "^2.8.1",
    "css-resolve-import": "^0.1.0",
    "fmerge": "^1.2.0",
    "glob": "^5.0.10",
    "hogan.js": "^3.0.2",
    "sqwish": "~0.2.2",
    "uglify-js": "^2.4.23"
  },
```

**Comment by fizker** [comment]
@gerhardsletten I have bumped it to v. 0.7.1, which I believe fixed your issue. Can you please test?

**Comment by gerhardsletten** [comment]
Yes, can confirm that this bug is now gone!

Thank you very much!
